version: 2
jobs:
  build:
    working_directory: /go/src/github.com/dozen/ruby-marshal
    docker:
      - image: circleci/golang
    steps:
      - checkout
      - run: go get ./...
      - run: go test -v -race ./...
